# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.persoon import Persoon

class TestPersoon(unittest.TestCase):
    """Persoon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Persoon:
        """Test Persoon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Persoon`
        """
        model = Persoon()
        if include_optional:
            return Persoon(
                id = '',
                type = 'Persoon',
                persoon_voornaam = '',
                persoon_achternaam = '',
                persoon_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                persoon_inwonerschap = [
                    openapi_client.models.inwonerschap.Inwonerschap(
                        @type = 'Inwonerschap', 
                        heeft_verblijfplaats = null, )
                    ]
            )
        else:
            return Persoon(
                id = '',
                type = 'Persoon',
        )
        """

    def testPersoon(self):
        """Test Persoon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
