# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.publieke_organisatie_publieke_organisatie_type_skos_pref_label import PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel

class TestPubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel(unittest.TestCase):
    """PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel:
        """Test PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel`
        """
        model = PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel()
        if include_optional:
            return PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel(
                value = 'VDAB',
                language = 'nl'
            )
        else:
            return PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel(
                value = 'VDAB',
                language = 'nl',
        )
        """

    def testPubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel(self):
        """Test PubliekeOrganisatiePubliekeOrganisatieTypeSKOSPrefLabel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
