# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.deeltraject_deeltraject_status import DeeltrajectDeeltrajectStatus

class TestDeeltrajectDeeltrajectStatus(unittest.TestCase):
    """DeeltrajectDeeltrajectStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeeltrajectDeeltrajectStatus:
        """Test DeeltrajectDeeltrajectStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeeltrajectDeeltrajectStatus`
        """
        model = DeeltrajectDeeltrajectStatus()
        if include_optional:
            return DeeltrajectDeeltrajectStatus(
                id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief',
                skos_pref_label = openapi_client.models.deeltraject_deeltraject_status_skos_pref_label.Deeltraject_Deeltraject_status_SKOS_prefLabel(
                    @value = 'Actief', 
                    @language = 'nl', )
            )
        else:
            return DeeltrajectDeeltrajectStatus(
                id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief',
                skos_pref_label = openapi_client.models.deeltraject_deeltraject_status_skos_pref_label.Deeltraject_Deeltraject_status_SKOS_prefLabel(
                    @value = 'Actief', 
                    @language = 'nl', ),
        )
        """

    def testDeeltrajectDeeltrajectStatus(self):
        """Test DeeltrajectDeeltrajectStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
