# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inwonerschap import Inwonerschap

class TestInwonerschap(unittest.TestCase):
    """Inwonerschap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Inwonerschap:
        """Test Inwonerschap
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Inwonerschap`
        """
        model = Inwonerschap()
        if include_optional:
            return Inwonerschap(
                type = 'Inwonerschap',
                heeft_verblijfplaats = None
            )
        else:
            return Inwonerschap(
        )
        """

    def testInwonerschap(self):
        """Test Inwonerschap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
