# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.adresvoorstelling_adresvoorstelling_postcode import AdresvoorstellingAdresvoorstellingPostcode

class TestAdresvoorstellingAdresvoorstellingPostcode(unittest.TestCase):
    """AdresvoorstellingAdresvoorstellingPostcode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdresvoorstellingAdresvoorstellingPostcode:
        """Test AdresvoorstellingAdresvoorstellingPostcode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdresvoorstellingAdresvoorstellingPostcode`
        """
        model = AdresvoorstellingAdresvoorstellingPostcode()
        if include_optional:
            return AdresvoorstellingAdresvoorstellingPostcode(
                value = ''
            )
        else:
            return AdresvoorstellingAdresvoorstellingPostcode(
                value = '',
        )
        """

    def testAdresvoorstellingAdresvoorstellingPostcode(self):
        """Test AdresvoorstellingAdresvoorstellingPostcode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
