# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.participatie import Participatie

class TestParticipatie(unittest.TestCase):
    """Participatie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Participatie:
        """Test Participatie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Participatie`
        """
        model = Participatie()
        if include_optional:
            return Participatie(
                id = '',
                type = 'Participatie',
                participatie_rol = openapi_client.models.participatie_participatie_rol.Participatie_Participatie_rol(
                    @id = 'https://data.vlaanderen.be/id/concept/Participatietype/Werkzoekende', 
                    skos/pref_label = openapi_client.models.participatie_participatie_rol_skos_pref_label.Participatie_Participatie_rol_SKOS_prefLabel(
                        @value = 'Werkzoekende', 
                        @language = 'nl', ), ),
                participatie_heeft_participant = openapi_client.models.participatie_participatie_heeft_participant.Participatie_Participatie_heeftParticipant(
                    @id = '', )
            )
        else:
            return Participatie(
                id = '',
                type = 'Participatie',
        )
        """

    def testParticipatie(self):
        """Test Participatie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
