# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.geregistreerd_persoon import GeregistreerdPersoon

class TestGeregistreerdPersoon(unittest.TestCase):
    """GeregistreerdPersoon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeregistreerdPersoon:
        """Test GeregistreerdPersoon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeregistreerdPersoon`
        """
        model = GeregistreerdPersoon()
        if include_optional:
            return GeregistreerdPersoon(
                id = '',
                type = 'GeregistreerdPersoon',
                geregistreerd_persoon_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                geregistreerd_persoon_voornaam = '',
                geregistreerd_persoon_achternaam = '',
                geregistreerd_persoon_werkvoorkeuren = [
                    openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner.GeregistreerdPersoon_GeregistreerdPersoon_werkvoorkeuren_inner(
                        @id = '', )
                    ],
                geregistreerd_persoon_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                geregistreerd_persoon_inwonerschap = [
                    openapi_client.models.inwonerschap.Inwonerschap(
                        @type = 'Inwonerschap', 
                        heeft_verblijfplaats = null, )
                    ]
            )
        else:
            return GeregistreerdPersoon(
                id = '',
                type = 'GeregistreerdPersoon',
                geregistreerd_persoon_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
        )
        """

    def testGeregistreerdPersoon(self):
        """Test GeregistreerdPersoon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
