# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_ld_root_graph_inner import JsonLdRootGraphInner

class TestJsonLdRootGraphInner(unittest.TestCase):
    """JsonLdRootGraphInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonLdRootGraphInner:
        """Test JsonLdRootGraphInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonLdRootGraphInner`
        """
        model = JsonLdRootGraphInner()
        if include_optional:
            return JsonLdRootGraphInner(
                id = '',
                type = 'Adresvoorstelling',
                werkvoorkeuren_beroep = [
                    openapi_client.models.beroepstoestand.Beroepstoestand(
                        @type = 'Beroepstoestand', 
                        beroepstoestand/naam = openapi_client.models.beroepstoestand_beroepstoestand_naam.Beroepstoestand_Beroepstoestand_naam(
                            @value = '', 
                            @language = 'nl', ), 
                        beroepstoestand/voorkeur = openapi_client.models.beroepstoestand_beroepstoestand_voorkeur.Beroepstoestand_Beroepstoestand_voorkeur(
                            @id = 'http://data.vlaanderen.be/id/concept/Voorkeurtype/UitgeslotenBeroep', 
                            skos/pref_label = openapi_client.models.beroepstoestand_beroepstoestand_voorkeur_skos_pref_label.Beroepstoestand_Beroepstoestand_voorkeur_SKOS_prefLabel(
                                @value = 'Uitgesloten Beroep', 
                                @language = 'nl', ), ), )
                    ],
                geregistreerd_persoon_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                geregistreerd_persoon_voornaam = '',
                geregistreerd_persoon_achternaam = '',
                geregistreerd_persoon_werkvoorkeuren = [
                    openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner.GeregistreerdPersoon_GeregistreerdPersoon_werkvoorkeuren_inner(
                        @id = '', )
                    ],
                geregistreerd_persoon_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                geregistreerd_persoon_inwonerschap = [
                    openapi_client.models.inwonerschap.Inwonerschap(
                        @type = 'Inwonerschap', 
                        heeft_verblijfplaats = null, )
                    ],
                persoon_voornaam = '',
                persoon_achternaam = '',
                persoon_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                persoon_inwonerschap = [
                    openapi_client.models.inwonerschap.Inwonerschap(
                        @type = 'Inwonerschap', 
                        heeft_verblijfplaats = null, )
                    ],
                publieke_organisatie_voorkeursnaam = openapi_client.models.publieke_organisatie_publieke_organisatie_voorkeursnaam.PubliekeOrganisatie_PubliekeOrganisatie_voorkeursnaam(
                    @value = '', 
                    @language = 'nl', ),
                publieke_organisatie_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                publieke_organisatie_identificator = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                publieke_organisatie_type = openapi_client.models.publieke_organisatie_publieke_organisatie_type.PubliekeOrganisatie_PubliekeOrganisatie_type(
                    @id = 'https://data.vlaanderen.be/id/concept/OrganisatieType/VDAB', 
                    skos/pref_label = openapi_client.models.publieke_organisatie_publieke_organisatie_type_skos_pref_label.PubliekeOrganisatie_PubliekeOrganisatie_type_SKOS_prefLabel(
                        @value = 'VDAB', 
                        @language = 'nl', ), ),
                geregistreerde_organisatie_voorkeursnaam = openapi_client.models.geregistreerde_organisatie_geregistreerde_organisatie_voorkeursnaam.GeregistreerdeOrganisatie_GeregistreerdeOrganisatie_voorkeursnaam(
                    @value = '', 
                    @language = 'nl', ),
                geregistreerde_organisatie_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                geregistreerde_organisatie_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                geregistreerde_organisatie_type = openapi_client.models.publieke_organisatie_publieke_organisatie_type.PubliekeOrganisatie_PubliekeOrganisatie_type(
                    @id = 'https://data.vlaanderen.be/id/concept/OrganisatieType/VDAB', 
                    skos/pref_label = openapi_client.models.publieke_organisatie_publieke_organisatie_type_skos_pref_label.PubliekeOrganisatie_PubliekeOrganisatie_type_SKOS_prefLabel(
                        @value = 'VDAB', 
                        @language = 'nl', ), ),
                participatie_rol = openapi_client.models.participatie_participatie_rol.Participatie_Participatie_rol(
                    @id = 'https://data.vlaanderen.be/id/concept/Participatietype/Werkzoekende', 
                    skos/pref_label = openapi_client.models.participatie_participatie_rol_skos_pref_label.Participatie_Participatie_rol_SKOS_prefLabel(
                        @value = 'Werkzoekende', 
                        @language = 'nl', ), ),
                participatie_heeft_participant = openapi_client.models.participatie_participatie_heeft_participant.Participatie_Participatie_heeftParticipant(
                    @id = '', ),
                publieke_dienstverlening_naam = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_naam.PubliekeDienstverlening_PubliekeDienstverlening_naam(
                    @value = '', 
                    @language = '', ),
                publieke_dienstverlening_heeft_verantwoordelijke = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_verantwoordelijke.PubliekeDienstverlening_PubliekeDienstverlening_heeftVerantwoordelijke(
                    @id = '', ),
                publieke_dienstverlening_heeft_participatie = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                        @id = '', )
                    ],
                publieke_dienstverlening_gebruikt = [
                    openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner.GeregistreerdPersoon_GeregistreerdPersoon_werkvoorkeuren_inner(
                        @id = '', )
                    ],
                publieke_dienstverlening_produceert = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_produceert_inner.PubliekeDienstverlening_PubliekeDienstverlening_produceert_inner(
                        @id = '', )
                    ],
                publieke_dienstverlening_type = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type.PubliekeDienstverlening_PubliekeDienstverlening_type(
                    @id = 'https://data.vlaanderen.be/id/concept/PubliekeDienstverleningType/ActiveringNaarWerk', 
                    skos/pref_label = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type_skos_pref_label.PubliekeDienstverlening_PubliekeDienstverlening_type_SKOS_prefLabel(
                        @value = 'Activering Naar Werk', 
                        @language = 'nl', ), ),
                publieke_dienstverlening_finaliteit = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_finaliteit.PubliekeDienstverlening_PubliekeDienstverlening_finaliteit(
                    @id = 'https://data.vlaanderen.be/id/concept/FinaliteitType/SociaalOnderzoek', 
                    skos/pref_label = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_finaliteit_skos_pref_label.PubliekeDienstverlening_PubliekeDienstverlening_finaliteit_SKOS_prefLabel(
                        @value = 'Sociaal Onderzoek', 
                        @language = 'nl', ), ),
                activeringstraject_naam = openapi_client.models.activeringstraject_activeringstraject_naam.Activeringstraject_Activeringstraject_naam(
                    @value = '', 
                    @language = 'nl', ),
                activeringstraject_startdatum = openapi_client.models.activeringstraject_activeringstraject_startdatum.Activeringstraject_Activeringstraject_startdatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                activeringstraject_einddatum = openapi_client.models.activeringstraject_activeringstraject_einddatum.Activeringstraject_Activeringstraject_einddatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                activeringstraject_status = openapi_client.models.activeringstraject_activeringstraject_status.Activeringstraject_Activeringstraject_status(
                    @id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief', 
                    skos/pref_label = openapi_client.models.activeringstraject_activeringstraject_status_skos_pref_label.Activeringstraject_Activeringstraject_status_SKOS_prefLabel(
                        @value = 'Actief', 
                        @language = 'nl', ), ),
                activeringstraject_deeltraject = [
                    openapi_client.models.deeltraject.Deeltraject(
                        @id = '', 
                        @type = 'Deeltraject', 
                        deeltraject/naam = openapi_client.models.deeltraject_deeltraject_naam.Deeltraject_Deeltraject_naam(
                            @value = '', 
                            @language = 'nl', ), 
                        deeltraject/startdatum = openapi_client.models.deeltraject_deeltraject_startdatum.Deeltraject_Deeltraject_startdatum(
                            @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            @type = 'DateTime', ), 
                        deeltraject/einddatum = openapi_client.models.deeltraject_deeltraject_einddatum.Deeltraject_Deeltraject_einddatum(
                            @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            @type = 'DateTime', ), 
                        deeltraject/type = openapi_client.models.deeltraject_deeltraject_type.Deeltraject_Deeltraject_type(
                            @id = 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Opleiding', ), 
                        deeltraject/status = openapi_client.models.deeltraject_deeltraject_status.Deeltraject_Deeltraject_status(
                            @id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief', 
                            skos/pref_label = openapi_client.models.deeltraject_deeltraject_status_skos_pref_label.Deeltraject_Deeltraject_status_SKOS_prefLabel(
                                @value = 'Actief', 
                                @language = 'nl', ), ), 
                        deeltraject/heeft_participatie = [
                            openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                                @id = '', )
                            ], )
                    ],
                activeringstraject_heeft_participatie = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                        @id = '', )
                    ],
                deeltraject_naam = openapi_client.models.deeltraject_deeltraject_naam.Deeltraject_Deeltraject_naam(
                    @value = '', 
                    @language = 'nl', ),
                deeltraject_startdatum = openapi_client.models.deeltraject_deeltraject_startdatum.Deeltraject_Deeltraject_startdatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                deeltraject_einddatum = openapi_client.models.deeltraject_deeltraject_einddatum.Deeltraject_Deeltraject_einddatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                deeltraject_type = openapi_client.models.deeltraject_deeltraject_type.Deeltraject_Deeltraject_type(
                    @id = 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Opleiding', ),
                deeltraject_status = openapi_client.models.deeltraject_deeltraject_status.Deeltraject_Deeltraject_status(
                    @id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief', 
                    skos/pref_label = openapi_client.models.deeltraject_deeltraject_status_skos_pref_label.Deeltraject_Deeltraject_status_SKOS_prefLabel(
                        @value = 'Actief', 
                        @language = 'nl', ), ),
                deeltraject_heeft_participatie = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                        @id = '', )
                    ],
                verblijfplaats_verblijfsadres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                    @id = '', ),
                adresvoorstelling_straatnaam = openapi_client.models.adresvoorstelling_adresvoorstelling_straatnaam.Adresvoorstelling_Adresvoorstelling_straatnaam(
                    @value = '', 
                    @language = 'nl', ),
                adresvoorstelling_straatcode = openapi_client.models.adresvoorstelling_adresvoorstelling_straatcode.Adresvoorstelling_Adresvoorstelling_straatcode(
                    @value = '', ),
                adresvoorstelling_busnummer = openapi_client.models.adresvoorstelling_adresvoorstelling_busnummer.Adresvoorstelling_Adresvoorstelling_busnummer(
                    @value = '', ),
                adresvoorstelling_huisnummer = openapi_client.models.adresvoorstelling_adresvoorstelling_huisnummer.Adresvoorstelling_Adresvoorstelling_huisnummer(
                    @value = '', ),
                adresvoorstelling_postcode = openapi_client.models.adresvoorstelling_adresvoorstelling_postcode.Adresvoorstelling_Adresvoorstelling_postcode(
                    @value = '', ),
                adresvoorstelling_gemeentenaam = openapi_client.models.adresvoorstelling_adresvoorstelling_gemeentenaam.Adresvoorstelling_Adresvoorstelling_gemeentenaam(
                    @value = '', 
                    @language = 'nl', ),
                adresvoorstelling_gemeentecode = openapi_client.models.adresvoorstelling_adresvoorstelling_gemeentecode.Adresvoorstelling_Adresvoorstelling_gemeentecode(
                    @value = '', ),
                adresvoorstelling_land = openapi_client.models.adresvoorstelling_adresvoorstelling_land.Adresvoorstelling_Adresvoorstelling_land(
                    @value = '', 
                    @language = 'nl', )
            )
        else:
            return JsonLdRootGraphInner(
                id = '',
                type = 'Adresvoorstelling',
                geregistreerd_persoon_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                geregistreerde_organisatie_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                publieke_dienstverlening_naam = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_naam.PubliekeDienstverlening_PubliekeDienstverlening_naam(
                    @value = '', 
                    @language = '', ),
                publieke_dienstverlening_heeft_verantwoordelijke = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_verantwoordelijke.PubliekeDienstverlening_PubliekeDienstverlening_heeftVerantwoordelijke(
                    @id = '', ),
                activeringstraject_naam = openapi_client.models.activeringstraject_activeringstraject_naam.Activeringstraject_Activeringstraject_naam(
                    @value = '', 
                    @language = 'nl', ),
        )
        """

    def testJsonLdRootGraphInner(self):
        """Test JsonLdRootGraphInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
