# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activeringstraject_activeringstraject_einddatum import ActiveringstrajectActiveringstrajectEinddatum

class TestActiveringstrajectActiveringstrajectEinddatum(unittest.TestCase):
    """ActiveringstrajectActiveringstrajectEinddatum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveringstrajectActiveringstrajectEinddatum:
        """Test ActiveringstrajectActiveringstrajectEinddatum
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveringstrajectActiveringstrajectEinddatum`
        """
        model = ActiveringstrajectActiveringstrajectEinddatum()
        if include_optional:
            return ActiveringstrajectActiveringstrajectEinddatum(
                value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'DateTime'
            )
        else:
            return ActiveringstrajectActiveringstrajectEinddatum(
                value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'DateTime',
        )
        """

    def testActiveringstrajectActiveringstrajectEinddatum(self):
        """Test ActiveringstrajectActiveringstrajectEinddatum"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
