# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner import GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner

class TestGeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner(unittest.TestCase):
    """GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner:
        """Test GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner`
        """
        model = GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner()
        if include_optional:
            return GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner(
                id = ''
            )
        else:
            return GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner(
                id = '',
        )
        """

    def testGeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner(self):
        """Test GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
