# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.activeringstraject_activeringstraject_einddatum import ActiveringstrajectActiveringstrajectEinddatum
from openapi_client.models.activeringstraject_activeringstraject_naam import ActiveringstrajectActiveringstrajectNaam
from openapi_client.models.activeringstraject_activeringstraject_startdatum import ActiveringstrajectActiveringstrajectStartdatum
from openapi_client.models.activeringstraject_activeringstraject_status import ActiveringstrajectActiveringstrajectStatus
from openapi_client.models.deeltraject import Deeltraject
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner import PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner
from typing import Optional, Set
from typing_extensions import Self

class Activeringstraject(BaseModel):
    """
    Een Activeringstraject is een specifiekere variant van een Traject dat moet aansporen om de Werkzoekende te activeren naar werk.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    activeringstraject_naam: ActiveringstrajectActiveringstrajectNaam = Field(alias="Activeringstraject.naam")
    activeringstraject_startdatum: Optional[ActiveringstrajectActiveringstrajectStartdatum] = Field(default=None, alias="Activeringstraject.startdatum")
    activeringstraject_einddatum: Optional[ActiveringstrajectActiveringstrajectEinddatum] = Field(default=None, alias="Activeringstraject.einddatum")
    activeringstraject_status: Optional[ActiveringstrajectActiveringstrajectStatus] = Field(default=None, alias="Activeringstraject.status")
    activeringstraject_deeltraject: Optional[Annotated[List[Deeltraject], Field(min_length=0)]] = Field(default=None, description="De Deeltrajecten gelinkt aan dit Traject.", alias="Activeringstraject.deeltraject")
    activeringstraject_heeft_participatie: Optional[Annotated[List[PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner], Field(min_length=0)]] = Field(default=None, alias="Activeringstraject.heeftParticipatie")
    __properties: ClassVar[List[str]] = ["@id", "@type", "Activeringstraject.naam", "Activeringstraject.startdatum", "Activeringstraject.einddatum", "Activeringstraject.status", "Activeringstraject.deeltraject", "Activeringstraject.heeftParticipatie"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Activeringstraject']):
            raise ValueError("must be one of enum values ('Activeringstraject')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Activeringstraject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of activeringstraject_naam
        if self.activeringstraject_naam:
            _dict['Activeringstraject.naam'] = self.activeringstraject_naam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of activeringstraject_startdatum
        if self.activeringstraject_startdatum:
            _dict['Activeringstraject.startdatum'] = self.activeringstraject_startdatum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of activeringstraject_einddatum
        if self.activeringstraject_einddatum:
            _dict['Activeringstraject.einddatum'] = self.activeringstraject_einddatum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of activeringstraject_status
        if self.activeringstraject_status:
            _dict['Activeringstraject.status'] = self.activeringstraject_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in activeringstraject_deeltraject (list)
        _items = []
        if self.activeringstraject_deeltraject:
            for _item_activeringstraject_deeltraject in self.activeringstraject_deeltraject:
                if _item_activeringstraject_deeltraject:
                    _items.append(_item_activeringstraject_deeltraject.to_dict())
            _dict['Activeringstraject.deeltraject'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activeringstraject_heeft_participatie (list)
        _items = []
        if self.activeringstraject_heeft_participatie:
            for _item_activeringstraject_heeft_participatie in self.activeringstraject_heeft_participatie:
                if _item_activeringstraject_heeft_participatie:
                    _items.append(_item_activeringstraject_heeft_participatie.to_dict())
            _dict['Activeringstraject.heeftParticipatie'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Activeringstraject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "Activeringstraject.naam": ActiveringstrajectActiveringstrajectNaam.from_dict(obj["Activeringstraject.naam"]) if obj.get("Activeringstraject.naam") is not None else None,
            "Activeringstraject.startdatum": ActiveringstrajectActiveringstrajectStartdatum.from_dict(obj["Activeringstraject.startdatum"]) if obj.get("Activeringstraject.startdatum") is not None else None,
            "Activeringstraject.einddatum": ActiveringstrajectActiveringstrajectEinddatum.from_dict(obj["Activeringstraject.einddatum"]) if obj.get("Activeringstraject.einddatum") is not None else None,
            "Activeringstraject.status": ActiveringstrajectActiveringstrajectStatus.from_dict(obj["Activeringstraject.status"]) if obj.get("Activeringstraject.status") is not None else None,
            "Activeringstraject.deeltraject": [Deeltraject.from_dict(_item) for _item in obj["Activeringstraject.deeltraject"]] if obj.get("Activeringstraject.deeltraject") is not None else None,
            "Activeringstraject.heeftParticipatie": [PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner.from_dict(_item) for _item in obj["Activeringstraject.heeftParticipatie"]] if obj.get("Activeringstraject.heeftParticipatie") is not None else None
        })
        return _obj


