# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.adresvoorstelling_adresvoorstelling_busnummer import AdresvoorstellingAdresvoorstellingBusnummer
from openapi_client.models.adresvoorstelling_adresvoorstelling_gemeentecode import AdresvoorstellingAdresvoorstellingGemeentecode
from openapi_client.models.adresvoorstelling_adresvoorstelling_gemeentenaam import AdresvoorstellingAdresvoorstellingGemeentenaam
from openapi_client.models.adresvoorstelling_adresvoorstelling_huisnummer import AdresvoorstellingAdresvoorstellingHuisnummer
from openapi_client.models.adresvoorstelling_adresvoorstelling_land import AdresvoorstellingAdresvoorstellingLand
from openapi_client.models.adresvoorstelling_adresvoorstelling_postcode import AdresvoorstellingAdresvoorstellingPostcode
from openapi_client.models.adresvoorstelling_adresvoorstelling_straatcode import AdresvoorstellingAdresvoorstellingStraatcode
from openapi_client.models.adresvoorstelling_adresvoorstelling_straatnaam import AdresvoorstellingAdresvoorstellingStraatnaam
from typing import Optional, Set
from typing_extensions import Self

class Adresvoorstelling(BaseModel):
    """
    Meer leesbare voorstelling met enkel de basisgegevens van het adres, bedoeld voor het gebruik van een adres als attribuut van een ander object.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    adresvoorstelling_straatnaam: Optional[AdresvoorstellingAdresvoorstellingStraatnaam] = Field(default=None, alias="Adresvoorstelling.straatnaam")
    adresvoorstelling_straatcode: Optional[AdresvoorstellingAdresvoorstellingStraatcode] = Field(default=None, alias="Adresvoorstelling.straatcode")
    adresvoorstelling_busnummer: Optional[AdresvoorstellingAdresvoorstellingBusnummer] = Field(default=None, alias="Adresvoorstelling.busnummer")
    adresvoorstelling_huisnummer: Optional[AdresvoorstellingAdresvoorstellingHuisnummer] = Field(default=None, alias="Adresvoorstelling.huisnummer")
    adresvoorstelling_postcode: Optional[AdresvoorstellingAdresvoorstellingPostcode] = Field(default=None, alias="Adresvoorstelling.postcode")
    adresvoorstelling_gemeentenaam: Optional[AdresvoorstellingAdresvoorstellingGemeentenaam] = Field(default=None, alias="Adresvoorstelling.gemeentenaam")
    adresvoorstelling_gemeentecode: Optional[AdresvoorstellingAdresvoorstellingGemeentecode] = Field(default=None, alias="Adresvoorstelling.gemeentecode")
    adresvoorstelling_land: Optional[AdresvoorstellingAdresvoorstellingLand] = Field(default=None, alias="Adresvoorstelling.land")
    __properties: ClassVar[List[str]] = ["@id", "@type", "Adresvoorstelling.straatnaam", "Adresvoorstelling.straatcode", "Adresvoorstelling.busnummer", "Adresvoorstelling.huisnummer", "Adresvoorstelling.postcode", "Adresvoorstelling.gemeentenaam", "Adresvoorstelling.gemeentecode", "Adresvoorstelling.land"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Adresvoorstelling']):
            raise ValueError("must be one of enum values ('Adresvoorstelling')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Adresvoorstelling from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_straatnaam
        if self.adresvoorstelling_straatnaam:
            _dict['Adresvoorstelling.straatnaam'] = self.adresvoorstelling_straatnaam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_straatcode
        if self.adresvoorstelling_straatcode:
            _dict['Adresvoorstelling.straatcode'] = self.adresvoorstelling_straatcode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_busnummer
        if self.adresvoorstelling_busnummer:
            _dict['Adresvoorstelling.busnummer'] = self.adresvoorstelling_busnummer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_huisnummer
        if self.adresvoorstelling_huisnummer:
            _dict['Adresvoorstelling.huisnummer'] = self.adresvoorstelling_huisnummer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_postcode
        if self.adresvoorstelling_postcode:
            _dict['Adresvoorstelling.postcode'] = self.adresvoorstelling_postcode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_gemeentenaam
        if self.adresvoorstelling_gemeentenaam:
            _dict['Adresvoorstelling.gemeentenaam'] = self.adresvoorstelling_gemeentenaam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_gemeentecode
        if self.adresvoorstelling_gemeentecode:
            _dict['Adresvoorstelling.gemeentecode'] = self.adresvoorstelling_gemeentecode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adresvoorstelling_land
        if self.adresvoorstelling_land:
            _dict['Adresvoorstelling.land'] = self.adresvoorstelling_land.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Adresvoorstelling from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "Adresvoorstelling.straatnaam": AdresvoorstellingAdresvoorstellingStraatnaam.from_dict(obj["Adresvoorstelling.straatnaam"]) if obj.get("Adresvoorstelling.straatnaam") is not None else None,
            "Adresvoorstelling.straatcode": AdresvoorstellingAdresvoorstellingStraatcode.from_dict(obj["Adresvoorstelling.straatcode"]) if obj.get("Adresvoorstelling.straatcode") is not None else None,
            "Adresvoorstelling.busnummer": AdresvoorstellingAdresvoorstellingBusnummer.from_dict(obj["Adresvoorstelling.busnummer"]) if obj.get("Adresvoorstelling.busnummer") is not None else None,
            "Adresvoorstelling.huisnummer": AdresvoorstellingAdresvoorstellingHuisnummer.from_dict(obj["Adresvoorstelling.huisnummer"]) if obj.get("Adresvoorstelling.huisnummer") is not None else None,
            "Adresvoorstelling.postcode": AdresvoorstellingAdresvoorstellingPostcode.from_dict(obj["Adresvoorstelling.postcode"]) if obj.get("Adresvoorstelling.postcode") is not None else None,
            "Adresvoorstelling.gemeentenaam": AdresvoorstellingAdresvoorstellingGemeentenaam.from_dict(obj["Adresvoorstelling.gemeentenaam"]) if obj.get("Adresvoorstelling.gemeentenaam") is not None else None,
            "Adresvoorstelling.gemeentecode": AdresvoorstellingAdresvoorstellingGemeentecode.from_dict(obj["Adresvoorstelling.gemeentecode"]) if obj.get("Adresvoorstelling.gemeentecode") is not None else None,
            "Adresvoorstelling.land": AdresvoorstellingAdresvoorstellingLand.from_dict(obj["Adresvoorstelling.land"]) if obj.get("Adresvoorstelling.land") is not None else None
        })
        return _obj


