# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.beroepstoestand_beroepstoestand_naam import BeroepstoestandBeroepstoestandNaam
from openapi_client.models.beroepstoestand_beroepstoestand_voorkeur import BeroepstoestandBeroepstoestandVoorkeur
from typing import Optional, Set
from typing_extensions import Self

class Beroepstoestand(BaseModel):
    """
    Voorkeur voor een bepaald beroep.
    """ # noqa: E501
    type: StrictStr = Field(description="Object type.", alias="@type")
    beroepstoestand_naam: Optional[BeroepstoestandBeroepstoestandNaam] = Field(default=None, alias="Beroepstoestand.naam")
    beroepstoestand_voorkeur: Optional[BeroepstoestandBeroepstoestandVoorkeur] = Field(default=None, alias="Beroepstoestand.voorkeur")
    __properties: ClassVar[List[str]] = ["@type", "Beroepstoestand.naam", "Beroepstoestand.voorkeur"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Beroepstoestand']):
            raise ValueError("must be one of enum values ('Beroepstoestand')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Beroepstoestand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of beroepstoestand_naam
        if self.beroepstoestand_naam:
            _dict['Beroepstoestand.naam'] = self.beroepstoestand_naam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of beroepstoestand_voorkeur
        if self.beroepstoestand_voorkeur:
            _dict['Beroepstoestand.voorkeur'] = self.beroepstoestand_voorkeur.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Beroepstoestand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "Beroepstoestand.naam": BeroepstoestandBeroepstoestandNaam.from_dict(obj["Beroepstoestand.naam"]) if obj.get("Beroepstoestand.naam") is not None else None,
            "Beroepstoestand.voorkeur": BeroepstoestandBeroepstoestandVoorkeur.from_dict(obj["Beroepstoestand.voorkeur"]) if obj.get("Beroepstoestand.voorkeur") is not None else None
        })
        return _obj


