# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.contactpunt import Contactpunt
from openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner import GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner
from openapi_client.models.identificator import Identificator
from openapi_client.models.inwonerschap import Inwonerschap
from typing import Optional, Set
from typing_extensions import Self

class GeregistreerdPersoon(BaseModel):
    """
    Persoon waarvan de gegevens zijn ingeschreven in een register.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    geregistreerd_persoon_registratie: Annotated[List[Identificator], Field(min_length=1)] = Field(description="Identificatiecode van de persoon in het register.", alias="GeregistreerdPersoon.registratie")
    geregistreerd_persoon_voornaam: Optional[StrictStr] = Field(default=None, description="Naam die een Persoon bij geboorte wordt gegeven. Onderscheidt de Persoon van de andere personen in de familie.", alias="GeregistreerdPersoon.voornaam")
    geregistreerd_persoon_achternaam: Optional[StrictStr] = Field(default=None, description="Gedeelte van de volledige naam van de Persoon ontvangen van de vorige generatie.", alias="GeregistreerdPersoon.achternaam")
    geregistreerd_persoon_werkvoorkeuren: Optional[Annotated[List[GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner], Field(min_length=0)]] = Field(default=None, description="De voorkeuren voor werk van een Persoon.", alias="GeregistreerdPersoon.werkvoorkeuren")
    geregistreerd_persoon_contactinfo: Optional[Annotated[List[Contactpunt], Field(min_length=0)]] = Field(default=None, description="Informatie zoals email, telefoon... die toelaat de Persoon te contacteren.", alias="GeregistreerdPersoon.contactinfo")
    geregistreerd_persoon_inwonerschap: Optional[Annotated[List[Inwonerschap], Field(min_length=0)]] = Field(default=None, description="Jurisdictie waarbinnen het Inwonerschap van de Persoon is gedefinieerd.", alias="GeregistreerdPersoon.inwonerschap")
    __properties: ClassVar[List[str]] = ["@id", "@type", "GeregistreerdPersoon.registratie", "GeregistreerdPersoon.voornaam", "GeregistreerdPersoon.achternaam", "GeregistreerdPersoon.werkvoorkeuren", "GeregistreerdPersoon.contactinfo", "GeregistreerdPersoon.inwonerschap"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['GeregistreerdPersoon']):
            raise ValueError("must be one of enum values ('GeregistreerdPersoon')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeregistreerdPersoon from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in geregistreerd_persoon_registratie (list)
        _items = []
        if self.geregistreerd_persoon_registratie:
            for _item_geregistreerd_persoon_registratie in self.geregistreerd_persoon_registratie:
                if _item_geregistreerd_persoon_registratie:
                    _items.append(_item_geregistreerd_persoon_registratie.to_dict())
            _dict['GeregistreerdPersoon.registratie'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in geregistreerd_persoon_werkvoorkeuren (list)
        _items = []
        if self.geregistreerd_persoon_werkvoorkeuren:
            for _item_geregistreerd_persoon_werkvoorkeuren in self.geregistreerd_persoon_werkvoorkeuren:
                if _item_geregistreerd_persoon_werkvoorkeuren:
                    _items.append(_item_geregistreerd_persoon_werkvoorkeuren.to_dict())
            _dict['GeregistreerdPersoon.werkvoorkeuren'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in geregistreerd_persoon_contactinfo (list)
        _items = []
        if self.geregistreerd_persoon_contactinfo:
            for _item_geregistreerd_persoon_contactinfo in self.geregistreerd_persoon_contactinfo:
                if _item_geregistreerd_persoon_contactinfo:
                    _items.append(_item_geregistreerd_persoon_contactinfo.to_dict())
            _dict['GeregistreerdPersoon.contactinfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in geregistreerd_persoon_inwonerschap (list)
        _items = []
        if self.geregistreerd_persoon_inwonerschap:
            for _item_geregistreerd_persoon_inwonerschap in self.geregistreerd_persoon_inwonerschap:
                if _item_geregistreerd_persoon_inwonerschap:
                    _items.append(_item_geregistreerd_persoon_inwonerschap.to_dict())
            _dict['GeregistreerdPersoon.inwonerschap'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeregistreerdPersoon from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "GeregistreerdPersoon.registratie": [Identificator.from_dict(_item) for _item in obj["GeregistreerdPersoon.registratie"]] if obj.get("GeregistreerdPersoon.registratie") is not None else None,
            "GeregistreerdPersoon.voornaam": obj.get("GeregistreerdPersoon.voornaam"),
            "GeregistreerdPersoon.achternaam": obj.get("GeregistreerdPersoon.achternaam"),
            "GeregistreerdPersoon.werkvoorkeuren": [GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner.from_dict(_item) for _item in obj["GeregistreerdPersoon.werkvoorkeuren"]] if obj.get("GeregistreerdPersoon.werkvoorkeuren") is not None else None,
            "GeregistreerdPersoon.contactinfo": [Contactpunt.from_dict(_item) for _item in obj["GeregistreerdPersoon.contactinfo"]] if obj.get("GeregistreerdPersoon.contactinfo") is not None else None,
            "GeregistreerdPersoon.inwonerschap": [Inwonerschap.from_dict(_item) for _item in obj["GeregistreerdPersoon.inwonerschap"]] if obj.get("GeregistreerdPersoon.inwonerschap") is not None else None
        })
        return _obj


