# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.contactpunt import Contactpunt
from openapi_client.models.geregistreerde_organisatie_geregistreerde_organisatie_voorkeursnaam import GeregistreerdeOrganisatieGeregistreerdeOrganisatieVoorkeursnaam
from openapi_client.models.identificator import Identificator
from openapi_client.models.publieke_organisatie_publieke_organisatie_type import PubliekeOrganisatiePubliekeOrganisatieType
from typing import Optional, Set
from typing_extensions import Self

class GeregistreerdeOrganisatie(BaseModel):
    """
    Organisatie met een juridisch statuut vastgelegd door registratie. Vergelijk met een FormeleOrganisatie waarbij dit statuut ook op een andere manier verkregen kan zijn.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    geregistreerde_organisatie_voorkeursnaam: Optional[GeregistreerdeOrganisatieGeregistreerdeOrganisatieVoorkeursnaam] = Field(default=None, alias="GeregistreerdeOrganisatie.voorkeursnaam")
    geregistreerde_organisatie_registratie: Annotated[List[Identificator], Field(min_length=0)] = Field(alias="GeregistreerdeOrganisatie.registratie")
    geregistreerde_organisatie_contactinfo: Optional[Annotated[List[Contactpunt], Field(min_length=0)]] = Field(default=None, description="Informatie zoals email, telefoon... die toelaat de Organisatie te contacteren.", alias="GeregistreerdeOrganisatie.contactinfo")
    geregistreerde_organisatie_type: Optional[PubliekeOrganisatiePubliekeOrganisatieType] = Field(default=None, alias="GeregistreerdeOrganisatie.type")
    __properties: ClassVar[List[str]] = ["@id", "@type", "GeregistreerdeOrganisatie.voorkeursnaam", "GeregistreerdeOrganisatie.registratie", "GeregistreerdeOrganisatie.contactinfo", "GeregistreerdeOrganisatie.type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['GeregistreerdeOrganisatie']):
            raise ValueError("must be one of enum values ('GeregistreerdeOrganisatie')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeregistreerdeOrganisatie from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of geregistreerde_organisatie_voorkeursnaam
        if self.geregistreerde_organisatie_voorkeursnaam:
            _dict['GeregistreerdeOrganisatie.voorkeursnaam'] = self.geregistreerde_organisatie_voorkeursnaam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in geregistreerde_organisatie_registratie (list)
        _items = []
        if self.geregistreerde_organisatie_registratie:
            for _item_geregistreerde_organisatie_registratie in self.geregistreerde_organisatie_registratie:
                if _item_geregistreerde_organisatie_registratie:
                    _items.append(_item_geregistreerde_organisatie_registratie.to_dict())
            _dict['GeregistreerdeOrganisatie.registratie'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in geregistreerde_organisatie_contactinfo (list)
        _items = []
        if self.geregistreerde_organisatie_contactinfo:
            for _item_geregistreerde_organisatie_contactinfo in self.geregistreerde_organisatie_contactinfo:
                if _item_geregistreerde_organisatie_contactinfo:
                    _items.append(_item_geregistreerde_organisatie_contactinfo.to_dict())
            _dict['GeregistreerdeOrganisatie.contactinfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of geregistreerde_organisatie_type
        if self.geregistreerde_organisatie_type:
            _dict['GeregistreerdeOrganisatie.type'] = self.geregistreerde_organisatie_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeregistreerdeOrganisatie from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "GeregistreerdeOrganisatie.voorkeursnaam": GeregistreerdeOrganisatieGeregistreerdeOrganisatieVoorkeursnaam.from_dict(obj["GeregistreerdeOrganisatie.voorkeursnaam"]) if obj.get("GeregistreerdeOrganisatie.voorkeursnaam") is not None else None,
            "GeregistreerdeOrganisatie.registratie": [Identificator.from_dict(_item) for _item in obj["GeregistreerdeOrganisatie.registratie"]] if obj.get("GeregistreerdeOrganisatie.registratie") is not None else None,
            "GeregistreerdeOrganisatie.contactinfo": [Contactpunt.from_dict(_item) for _item in obj["GeregistreerdeOrganisatie.contactinfo"]] if obj.get("GeregistreerdeOrganisatie.contactinfo") is not None else None,
            "GeregistreerdeOrganisatie.type": PubliekeOrganisatiePubliekeOrganisatieType.from_dict(obj["GeregistreerdeOrganisatie.type"]) if obj.get("GeregistreerdeOrganisatie.type") is not None else None
        })
        return _obj


