# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.contactpunt import Contactpunt
from openapi_client.models.inwonerschap import Inwonerschap
from typing import Optional, Set
from typing_extensions import Self

class Persoon(BaseModel):
    """
    Natuurlijk persoon.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    persoon_voornaam: Optional[StrictStr] = Field(default=None, description="Naam die een Persoon bij geboorte wordt gegeven. Onderscheidt de Persoon van de andere personen in de familie.", alias="Persoon.voornaam")
    persoon_achternaam: Optional[StrictStr] = Field(default=None, description="Gedeelte van de volledige naam van de Persoon ontvangen van de vorige generatie.", alias="Persoon.achternaam")
    persoon_contactinfo: Optional[Annotated[List[Contactpunt], Field(min_length=0)]] = Field(default=None, description="Informatie zoals email, telefoon... die toelaat de Persoon te contacteren.", alias="Persoon.contactinfo")
    persoon_inwonerschap: Optional[Annotated[List[Inwonerschap], Field(min_length=0)]] = Field(default=None, description="Jurisdictie waarbinnen het Inwonerschap van de Persoon is gedefinieerd.", alias="Persoon.inwonerschap")
    __properties: ClassVar[List[str]] = ["@id", "@type", "Persoon.voornaam", "Persoon.achternaam", "Persoon.contactinfo", "Persoon.inwonerschap"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Persoon']):
            raise ValueError("must be one of enum values ('Persoon')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Persoon from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in persoon_contactinfo (list)
        _items = []
        if self.persoon_contactinfo:
            for _item_persoon_contactinfo in self.persoon_contactinfo:
                if _item_persoon_contactinfo:
                    _items.append(_item_persoon_contactinfo.to_dict())
            _dict['Persoon.contactinfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in persoon_inwonerschap (list)
        _items = []
        if self.persoon_inwonerschap:
            for _item_persoon_inwonerschap in self.persoon_inwonerschap:
                if _item_persoon_inwonerschap:
                    _items.append(_item_persoon_inwonerschap.to_dict())
            _dict['Persoon.inwonerschap'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Persoon from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "Persoon.voornaam": obj.get("Persoon.voornaam"),
            "Persoon.achternaam": obj.get("Persoon.achternaam"),
            "Persoon.contactinfo": [Contactpunt.from_dict(_item) for _item in obj["Persoon.contactinfo"]] if obj.get("Persoon.contactinfo") is not None else None,
            "Persoon.inwonerschap": [Inwonerschap.from_dict(_item) for _item in obj["Persoon.inwonerschap"]] if obj.get("Persoon.inwonerschap") is not None else None
        })
        return _obj


