# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner import GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_finaliteit import PubliekeDienstverleningPubliekeDienstverleningFinaliteit
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner import PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_verantwoordelijke import PubliekeDienstverleningPubliekeDienstverleningHeeftVerantwoordelijke
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_naam import PubliekeDienstverleningPubliekeDienstverleningNaam
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_produceert_inner import PubliekeDienstverleningPubliekeDienstverleningProduceertInner
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type import PubliekeDienstverleningPubliekeDienstverleningType
from typing import Optional, Set
from typing_extensions import Self

class PubliekeDienstverlening(BaseModel):
    """
    Een publieke dienstverlening is een geheel van verplichte of optioneel uitgevoerde of uitvoerbare acties door of in naam van een publieke organisatie. De dienstverlening is ten bate van een individu, een bedrijf, een andere publieke organisatie of groepen.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    publieke_dienstverlening_naam: PubliekeDienstverleningPubliekeDienstverleningNaam = Field(alias="PubliekeDienstverlening.naam")
    publieke_dienstverlening_heeft_verantwoordelijke: PubliekeDienstverleningPubliekeDienstverleningHeeftVerantwoordelijke = Field(alias="PubliekeDienstverlening.heeftVerantwoordelijke")
    publieke_dienstverlening_heeft_participatie: Optional[Annotated[List[PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner], Field(min_length=0)]] = Field(default=None, description="De Agenten die deelnemen aan de Publieke Dienstverlening.", alias="PubliekeDienstverlening.heeftParticipatie")
    publieke_dienstverlening_gebruikt: Optional[Annotated[List[GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner], Field(min_length=0)]] = Field(default=None, description="Referenties naar alle Inputs die de Publieke Dienstverlening gebruikt om een of meerdere Outputs te produceren.", alias="PubliekeDienstverlening.gebruikt")
    publieke_dienstverlening_produceert: Optional[Annotated[List[PubliekeDienstverleningPubliekeDienstverleningProduceertInner], Field(min_length=0)]] = Field(default=None, description="De referenties naar alle resources die de Publieke Dienstverlening produceert.", alias="PubliekeDienstverlening.produceert")
    publieke_dienstverlening_type: Optional[PubliekeDienstverleningPubliekeDienstverleningType] = Field(default=None, alias="PubliekeDienstverlening.type")
    publieke_dienstverlening_finaliteit: Optional[PubliekeDienstverleningPubliekeDienstverleningFinaliteit] = Field(default=None, alias="PubliekeDienstverlening.finaliteit")
    __properties: ClassVar[List[str]] = ["@id", "@type", "PubliekeDienstverlening.naam", "PubliekeDienstverlening.heeftVerantwoordelijke", "PubliekeDienstverlening.heeftParticipatie", "PubliekeDienstverlening.gebruikt", "PubliekeDienstverlening.produceert", "PubliekeDienstverlening.type", "PubliekeDienstverlening.finaliteit"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PubliekeDienstverlening']):
            raise ValueError("must be one of enum values ('PubliekeDienstverlening')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PubliekeDienstverlening from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of publieke_dienstverlening_naam
        if self.publieke_dienstverlening_naam:
            _dict['PubliekeDienstverlening.naam'] = self.publieke_dienstverlening_naam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of publieke_dienstverlening_heeft_verantwoordelijke
        if self.publieke_dienstverlening_heeft_verantwoordelijke:
            _dict['PubliekeDienstverlening.heeftVerantwoordelijke'] = self.publieke_dienstverlening_heeft_verantwoordelijke.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in publieke_dienstverlening_heeft_participatie (list)
        _items = []
        if self.publieke_dienstverlening_heeft_participatie:
            for _item_publieke_dienstverlening_heeft_participatie in self.publieke_dienstverlening_heeft_participatie:
                if _item_publieke_dienstverlening_heeft_participatie:
                    _items.append(_item_publieke_dienstverlening_heeft_participatie.to_dict())
            _dict['PubliekeDienstverlening.heeftParticipatie'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in publieke_dienstverlening_gebruikt (list)
        _items = []
        if self.publieke_dienstverlening_gebruikt:
            for _item_publieke_dienstverlening_gebruikt in self.publieke_dienstverlening_gebruikt:
                if _item_publieke_dienstverlening_gebruikt:
                    _items.append(_item_publieke_dienstverlening_gebruikt.to_dict())
            _dict['PubliekeDienstverlening.gebruikt'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in publieke_dienstverlening_produceert (list)
        _items = []
        if self.publieke_dienstverlening_produceert:
            for _item_publieke_dienstverlening_produceert in self.publieke_dienstverlening_produceert:
                if _item_publieke_dienstverlening_produceert:
                    _items.append(_item_publieke_dienstverlening_produceert.to_dict())
            _dict['PubliekeDienstverlening.produceert'] = _items
        # override the default output from pydantic by calling `to_dict()` of publieke_dienstverlening_type
        if self.publieke_dienstverlening_type:
            _dict['PubliekeDienstverlening.type'] = self.publieke_dienstverlening_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of publieke_dienstverlening_finaliteit
        if self.publieke_dienstverlening_finaliteit:
            _dict['PubliekeDienstverlening.finaliteit'] = self.publieke_dienstverlening_finaliteit.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PubliekeDienstverlening from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "PubliekeDienstverlening.naam": PubliekeDienstverleningPubliekeDienstverleningNaam.from_dict(obj["PubliekeDienstverlening.naam"]) if obj.get("PubliekeDienstverlening.naam") is not None else None,
            "PubliekeDienstverlening.heeftVerantwoordelijke": PubliekeDienstverleningPubliekeDienstverleningHeeftVerantwoordelijke.from_dict(obj["PubliekeDienstverlening.heeftVerantwoordelijke"]) if obj.get("PubliekeDienstverlening.heeftVerantwoordelijke") is not None else None,
            "PubliekeDienstverlening.heeftParticipatie": [PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner.from_dict(_item) for _item in obj["PubliekeDienstverlening.heeftParticipatie"]] if obj.get("PubliekeDienstverlening.heeftParticipatie") is not None else None,
            "PubliekeDienstverlening.gebruikt": [GeregistreerdPersoonGeregistreerdPersoonWerkvoorkeurenInner.from_dict(_item) for _item in obj["PubliekeDienstverlening.gebruikt"]] if obj.get("PubliekeDienstverlening.gebruikt") is not None else None,
            "PubliekeDienstverlening.produceert": [PubliekeDienstverleningPubliekeDienstverleningProduceertInner.from_dict(_item) for _item in obj["PubliekeDienstverlening.produceert"]] if obj.get("PubliekeDienstverlening.produceert") is not None else None,
            "PubliekeDienstverlening.type": PubliekeDienstverleningPubliekeDienstverleningType.from_dict(obj["PubliekeDienstverlening.type"]) if obj.get("PubliekeDienstverlening.type") is not None else None,
            "PubliekeDienstverlening.finaliteit": PubliekeDienstverleningPubliekeDienstverleningFinaliteit.from_dict(obj["PubliekeDienstverlening.finaliteit"]) if obj.get("PubliekeDienstverlening.finaliteit") is not None else None
        })
        return _obj


