# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.werkvoorkeuren import Werkvoorkeuren

class TestWerkvoorkeuren(unittest.TestCase):
    """Werkvoorkeuren unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Werkvoorkeuren:
        """Test Werkvoorkeuren
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Werkvoorkeuren`
        """
        model = Werkvoorkeuren()
        if include_optional:
            return Werkvoorkeuren(
                id = '',
                type = 'Werkvoorkeuren',
                werkvoorkeuren_beroep = [
                    openapi_client.models.beroepstoestand.Beroepstoestand(
                        @type = 'Beroepstoestand', 
                        beroepstoestand/naam = openapi_client.models.beroepstoestand_beroepstoestand_naam.Beroepstoestand_Beroepstoestand_naam(
                            @value = '', 
                            @language = 'nl', ), 
                        beroepstoestand/voorkeur = openapi_client.models.beroepstoestand_beroepstoestand_voorkeur.Beroepstoestand_Beroepstoestand_voorkeur(
                            @id = 'http://data.vlaanderen.be/id/concept/Voorkeurtype/UitgeslotenBeroep', 
                            skos/pref_label = openapi_client.models.beroepstoestand_beroepstoestand_voorkeur_skos_pref_label.Beroepstoestand_Beroepstoestand_voorkeur_SKOS_prefLabel(
                                @value = 'Uitgesloten Beroep', 
                                @language = 'nl', ), ), )
                    ]
            )
        else:
            return Werkvoorkeuren(
                id = '',
                type = 'Werkvoorkeuren',
        )
        """

    def testWerkvoorkeuren(self):
        """Test Werkvoorkeuren"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
