# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.deeltraject import Deeltraject

class TestDeeltraject(unittest.TestCase):
    """Deeltraject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deeltraject:
        """Test Deeltraject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Deeltraject`
        """
        model = Deeltraject()
        if include_optional:
            return Deeltraject(
                id = '',
                type = 'Deeltraject',
                deeltraject_naam = openapi_client.models.deeltraject_deeltraject_naam.Deeltraject_Deeltraject_naam(
                    @value = '', 
                    @language = 'nl', ),
                deeltraject_startdatum = openapi_client.models.deeltraject_deeltraject_startdatum.Deeltraject_Deeltraject_startdatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                deeltraject_einddatum = openapi_client.models.deeltraject_deeltraject_einddatum.Deeltraject_Deeltraject_einddatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                deeltraject_type = openapi_client.models.deeltraject_deeltraject_type.Deeltraject_Deeltraject_type(
                    @id = 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Opleiding', ),
                deeltraject_status = openapi_client.models.deeltraject_deeltraject_status.Deeltraject_Deeltraject_status(
                    @id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief', 
                    skos/pref_label = openapi_client.models.deeltraject_deeltraject_status_skos_pref_label.Deeltraject_Deeltraject_status_SKOS_prefLabel(
                        @value = 'Actief', 
                        @language = 'nl', ), ),
                deeltraject_heeft_participatie = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                        @id = '', )
                    ]
            )
        else:
            return Deeltraject(
                id = '',
                type = 'Deeltraject',
        )
        """

    def testDeeltraject(self):
        """Test Deeltraject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
