# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.adresvoorstelling import Adresvoorstelling

class TestAdresvoorstelling(unittest.TestCase):
    """Adresvoorstelling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Adresvoorstelling:
        """Test Adresvoorstelling
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Adresvoorstelling`
        """
        model = Adresvoorstelling()
        if include_optional:
            return Adresvoorstelling(
                id = '',
                type = 'Adresvoorstelling',
                adresvoorstelling_straatnaam = openapi_client.models.adresvoorstelling_adresvoorstelling_straatnaam.Adresvoorstelling_Adresvoorstelling_straatnaam(
                    @value = '', 
                    @language = 'nl', ),
                adresvoorstelling_straatcode = openapi_client.models.adresvoorstelling_adresvoorstelling_straatcode.Adresvoorstelling_Adresvoorstelling_straatcode(
                    @value = '', ),
                adresvoorstelling_busnummer = openapi_client.models.adresvoorstelling_adresvoorstelling_busnummer.Adresvoorstelling_Adresvoorstelling_busnummer(
                    @value = '', ),
                adresvoorstelling_huisnummer = openapi_client.models.adresvoorstelling_adresvoorstelling_huisnummer.Adresvoorstelling_Adresvoorstelling_huisnummer(
                    @value = '', ),
                adresvoorstelling_postcode = openapi_client.models.adresvoorstelling_adresvoorstelling_postcode.Adresvoorstelling_Adresvoorstelling_postcode(
                    @value = '', ),
                adresvoorstelling_gemeentenaam = openapi_client.models.adresvoorstelling_adresvoorstelling_gemeentenaam.Adresvoorstelling_Adresvoorstelling_gemeentenaam(
                    @value = '', 
                    @language = 'nl', ),
                adresvoorstelling_gemeentecode = openapi_client.models.adresvoorstelling_adresvoorstelling_gemeentecode.Adresvoorstelling_Adresvoorstelling_gemeentecode(
                    @value = '', ),
                adresvoorstelling_land = openapi_client.models.adresvoorstelling_adresvoorstelling_land.Adresvoorstelling_Adresvoorstelling_land(
                    @value = '', 
                    @language = 'nl', )
            )
        else:
            return Adresvoorstelling(
                type = 'Adresvoorstelling',
        )
        """

    def testAdresvoorstelling(self):
        """Test Adresvoorstelling"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
