# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.geregistreerde_organisatie import GeregistreerdeOrganisatie

class TestGeregistreerdeOrganisatie(unittest.TestCase):
    """GeregistreerdeOrganisatie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeregistreerdeOrganisatie:
        """Test GeregistreerdeOrganisatie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeregistreerdeOrganisatie`
        """
        model = GeregistreerdeOrganisatie()
        if include_optional:
            return GeregistreerdeOrganisatie(
                id = '',
                type = 'GeregistreerdeOrganisatie',
                geregistreerde_organisatie_voorkeursnaam = openapi_client.models.geregistreerde_organisatie_geregistreerde_organisatie_voorkeursnaam.GeregistreerdeOrganisatie_GeregistreerdeOrganisatie_voorkeursnaam(
                    @value = '', 
                    @language = 'nl', ),
                geregistreerde_organisatie_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
                geregistreerde_organisatie_contactinfo = [
                    openapi_client.models.contactpunt.Contactpunt(
                        @type = 'Contactpunt', 
                        contactpunt/telefoon = openapi_client.models.contactpunt_contactpunt_telefoon.Contactpunt_Contactpunt_telefoon(
                            @value = '', ), 
                        contactpunt/adres = openapi_client.models.contactpunt_contactpunt_adres.Contactpunt_Contactpunt_adres(
                            @id = '', ), 
                        contactpunt/email = openapi_client.models.contactpunt_contactpunt_email.Contactpunt_Contactpunt_email(
                            @value = '', ), )
                    ],
                geregistreerde_organisatie_type = openapi_client.models.publieke_organisatie_publieke_organisatie_type.PubliekeOrganisatie_PubliekeOrganisatie_type(
                    @id = 'https://data.vlaanderen.be/id/concept/OrganisatieType/VDAB', 
                    skos/pref_label = openapi_client.models.publieke_organisatie_publieke_organisatie_type_skos_pref_label.PubliekeOrganisatie_PubliekeOrganisatie_type_SKOS_prefLabel(
                        @value = 'VDAB', 
                        @language = 'nl', ), )
            )
        else:
            return GeregistreerdeOrganisatie(
                id = '',
                type = 'GeregistreerdeOrganisatie',
                geregistreerde_organisatie_registratie = [
                    openapi_client.models.identificator.Identificator(
                        @type = 'Identificator', 
                        identificator/identificator = '', 
                        identificator/toegekend_door(string) = '', )
                    ],
        )
        """

    def testGeregistreerdeOrganisatie(self):
        """Test GeregistreerdeOrganisatie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
