# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type import PubliekeDienstverleningPubliekeDienstverleningType

class TestPubliekeDienstverleningPubliekeDienstverleningType(unittest.TestCase):
    """PubliekeDienstverleningPubliekeDienstverleningType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PubliekeDienstverleningPubliekeDienstverleningType:
        """Test PubliekeDienstverleningPubliekeDienstverleningType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PubliekeDienstverleningPubliekeDienstverleningType`
        """
        model = PubliekeDienstverleningPubliekeDienstverleningType()
        if include_optional:
            return PubliekeDienstverleningPubliekeDienstverleningType(
                id = 'https://data.vlaanderen.be/id/concept/PubliekeDienstverleningType/ActiveringNaarWerk',
                skos_pref_label = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type_skos_pref_label.PubliekeDienstverlening_PubliekeDienstverlening_type_SKOS_prefLabel(
                    @value = 'Activering Naar Werk', 
                    @language = 'nl', )
            )
        else:
            return PubliekeDienstverleningPubliekeDienstverleningType(
                id = 'https://data.vlaanderen.be/id/concept/PubliekeDienstverleningType/ActiveringNaarWerk',
                skos_pref_label = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type_skos_pref_label.PubliekeDienstverlening_PubliekeDienstverlening_type_SKOS_prefLabel(
                    @value = 'Activering Naar Werk', 
                    @language = 'nl', ),
        )
        """

    def testPubliekeDienstverleningPubliekeDienstverleningType(self):
        """Test PubliekeDienstverleningPubliekeDienstverleningType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
