# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activeringstraject import Activeringstraject

class TestActiveringstraject(unittest.TestCase):
    """Activeringstraject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Activeringstraject:
        """Test Activeringstraject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Activeringstraject`
        """
        model = Activeringstraject()
        if include_optional:
            return Activeringstraject(
                id = '',
                type = 'Activeringstraject',
                activeringstraject_naam = openapi_client.models.activeringstraject_activeringstraject_naam.Activeringstraject_Activeringstraject_naam(
                    @value = '', 
                    @language = 'nl', ),
                activeringstraject_startdatum = openapi_client.models.activeringstraject_activeringstraject_startdatum.Activeringstraject_Activeringstraject_startdatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                activeringstraject_einddatum = openapi_client.models.activeringstraject_activeringstraject_einddatum.Activeringstraject_Activeringstraject_einddatum(
                    @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    @type = 'DateTime', ),
                activeringstraject_status = openapi_client.models.activeringstraject_activeringstraject_status.Activeringstraject_Activeringstraject_status(
                    @id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief', 
                    skos/pref_label = openapi_client.models.activeringstraject_activeringstraject_status_skos_pref_label.Activeringstraject_Activeringstraject_status_SKOS_prefLabel(
                        @value = 'Actief', 
                        @language = 'nl', ), ),
                activeringstraject_deeltraject = [
                    openapi_client.models.deeltraject.Deeltraject(
                        @id = '', 
                        @type = 'Deeltraject', 
                        deeltraject/naam = openapi_client.models.deeltraject_deeltraject_naam.Deeltraject_Deeltraject_naam(
                            @value = '', 
                            @language = 'nl', ), 
                        deeltraject/startdatum = openapi_client.models.deeltraject_deeltraject_startdatum.Deeltraject_Deeltraject_startdatum(
                            @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            @type = 'DateTime', ), 
                        deeltraject/einddatum = openapi_client.models.deeltraject_deeltraject_einddatum.Deeltraject_Deeltraject_einddatum(
                            @value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            @type = 'DateTime', ), 
                        deeltraject/type = openapi_client.models.deeltraject_deeltraject_type.Deeltraject_Deeltraject_type(
                            @id = 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Opleiding', ), 
                        deeltraject/status = openapi_client.models.deeltraject_deeltraject_status.Deeltraject_Deeltraject_status(
                            @id = 'https://data.vlaanderen.be/id/concept/TrajectStatus/Actief', 
                            skos/pref_label = openapi_client.models.deeltraject_deeltraject_status_skos_pref_label.Deeltraject_Deeltraject_status_SKOS_prefLabel(
                                @value = 'Actief', 
                                @language = 'nl', ), ), 
                        deeltraject/heeft_participatie = [
                            openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                                @id = '', )
                            ], )
                    ],
                activeringstraject_heeft_participatie = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                        @id = '', )
                    ]
            )
        else:
            return Activeringstraject(
                id = '',
                type = 'Activeringstraject',
                activeringstraject_naam = openapi_client.models.activeringstraject_activeringstraject_naam.Activeringstraject_Activeringstraject_naam(
                    @value = '', 
                    @language = 'nl', ),
        )
        """

    def testActiveringstraject(self):
        """Test Activeringstraject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
