# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_ld_root_concept_graph_inner import JsonLdRootConceptGraphInner

class TestJsonLdRootConceptGraphInner(unittest.TestCase):
    """JsonLdRootConceptGraphInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonLdRootConceptGraphInner:
        """Test JsonLdRootConceptGraphInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonLdRootConceptGraphInner`
        """
        model = JsonLdRootConceptGraphInner()
        if include_optional:
            return JsonLdRootConceptGraphInner(
                id = 'https://data.vlaanderen.be/id/conceptscheme/Deeltrajecttype',
                type = 'SKOS:Concept',
                skos_pref_label = openapi_client.models.deeltraject_concept_skos_pref_label.DeeltrajectConcept_SKOS_prefLabel(
                    @value = '', 
                    @language = 'nl', ),
                skos_definition = openapi_client.models.deeltraject_concept_skos_definition.DeeltrajectConcept_SKOS_definition(
                    @value = '', 
                    @language = 'nl', ),
                skos_inscheme = openapi_client.models.deeltraject_concept_skos_inscheme.DeeltrajectConcept_SKOS_inscheme(
                    @id = '', ),
                skos_top_concept_of = openapi_client.models.deeltraject_concept_skos_top_concept_of.DeeltrajectConcept_SKOS_topConceptOf(
                    @id = '', )
            )
        else:
            return JsonLdRootConceptGraphInner(
                id = 'https://data.vlaanderen.be/id/conceptscheme/Deeltrajecttype',
                type = 'SKOS:Concept',
                skos_pref_label = openapi_client.models.deeltraject_concept_skos_pref_label.DeeltrajectConcept_SKOS_prefLabel(
                    @value = '', 
                    @language = 'nl', ),
                skos_definition = openapi_client.models.deeltraject_concept_skos_definition.DeeltrajectConcept_SKOS_definition(
                    @value = '', 
                    @language = 'nl', ),
        )
        """

    def testJsonLdRootConceptGraphInner(self):
        """Test JsonLdRootConceptGraphInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
