# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.publieke_dienstverlening import PubliekeDienstverlening

class TestPubliekeDienstverlening(unittest.TestCase):
    """PubliekeDienstverlening unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PubliekeDienstverlening:
        """Test PubliekeDienstverlening
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PubliekeDienstverlening`
        """
        model = PubliekeDienstverlening()
        if include_optional:
            return PubliekeDienstverlening(
                id = '',
                type = 'PubliekeDienstverlening',
                publieke_dienstverlening_naam = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_naam.PubliekeDienstverlening_PubliekeDienstverlening_naam(
                    @value = '', 
                    @language = '', ),
                publieke_dienstverlening_heeft_verantwoordelijke = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_verantwoordelijke.PubliekeDienstverlening_PubliekeDienstverlening_heeftVerantwoordelijke(
                    @id = '', ),
                publieke_dienstverlening_heeft_participatie = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner.PubliekeDienstverlening_PubliekeDienstverlening_heeftParticipatie_inner(
                        @id = '', )
                    ],
                publieke_dienstverlening_gebruikt = [
                    openapi_client.models.geregistreerd_persoon_geregistreerd_persoon_werkvoorkeuren_inner.GeregistreerdPersoon_GeregistreerdPersoon_werkvoorkeuren_inner(
                        @id = '', )
                    ],
                publieke_dienstverlening_produceert = [
                    openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_produceert_inner.PubliekeDienstverlening_PubliekeDienstverlening_produceert_inner(
                        @id = '', )
                    ],
                publieke_dienstverlening_type = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type.PubliekeDienstverlening_PubliekeDienstverlening_type(
                    @id = 'https://data.vlaanderen.be/id/concept/PubliekeDienstverleningType/ActiveringNaarWerk', 
                    skos/pref_label = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_type_skos_pref_label.PubliekeDienstverlening_PubliekeDienstverlening_type_SKOS_prefLabel(
                        @value = 'Activering Naar Werk', 
                        @language = 'nl', ), ),
                publieke_dienstverlening_finaliteit = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_finaliteit.PubliekeDienstverlening_PubliekeDienstverlening_finaliteit(
                    @id = 'https://data.vlaanderen.be/id/concept/FinaliteitType/SociaalOnderzoek', 
                    skos/pref_label = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_finaliteit_skos_pref_label.PubliekeDienstverlening_PubliekeDienstverlening_finaliteit_SKOS_prefLabel(
                        @value = 'Sociaal Onderzoek', 
                        @language = 'nl', ), )
            )
        else:
            return PubliekeDienstverlening(
                id = '',
                type = 'PubliekeDienstverlening',
                publieke_dienstverlening_naam = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_naam.PubliekeDienstverlening_PubliekeDienstverlening_naam(
                    @value = '', 
                    @language = '', ),
                publieke_dienstverlening_heeft_verantwoordelijke = openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_verantwoordelijke.PubliekeDienstverlening_PubliekeDienstverlening_heeftVerantwoordelijke(
                    @id = '', ),
        )
        """

    def testPubliekeDienstverlening(self):
        """Test PubliekeDienstverlening"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
