# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.contactpunt_contactpunt_adres import ContactpuntContactpuntAdres
from openapi_client.models.contactpunt_contactpunt_email import ContactpuntContactpuntEmail
from openapi_client.models.contactpunt_contactpunt_telefoon import ContactpuntContactpuntTelefoon
from typing import Optional, Set
from typing_extensions import Self

class Contactpunt(BaseModel):
    """
    Informatie zoals email, telefoon, adres die toelaat om iemand of iets te contacteren.
    """ # noqa: E501
    type: StrictStr = Field(description="Object type.", alias="@type")
    contactpunt_telefoon: Optional[ContactpuntContactpuntTelefoon] = Field(default=None, alias="Contactpunt.telefoon")
    contactpunt_adres: Optional[ContactpuntContactpuntAdres] = Field(default=None, alias="Contactpunt.adres")
    contactpunt_email: Optional[ContactpuntContactpuntEmail] = Field(default=None, alias="Contactpunt.email")
    __properties: ClassVar[List[str]] = ["@type", "Contactpunt.telefoon", "Contactpunt.adres", "Contactpunt.email"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Contactpunt']):
            raise ValueError("must be one of enum values ('Contactpunt')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Contactpunt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of contactpunt_telefoon
        if self.contactpunt_telefoon:
            _dict['Contactpunt.telefoon'] = self.contactpunt_telefoon.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contactpunt_adres
        if self.contactpunt_adres:
            _dict['Contactpunt.adres'] = self.contactpunt_adres.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contactpunt_email
        if self.contactpunt_email:
            _dict['Contactpunt.email'] = self.contactpunt_email.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Contactpunt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@type": obj.get("@type"),
            "Contactpunt.telefoon": ContactpuntContactpuntTelefoon.from_dict(obj["Contactpunt.telefoon"]) if obj.get("Contactpunt.telefoon") is not None else None,
            "Contactpunt.adres": ContactpuntContactpuntAdres.from_dict(obj["Contactpunt.adres"]) if obj.get("Contactpunt.adres") is not None else None,
            "Contactpunt.email": ContactpuntContactpuntEmail.from_dict(obj["Contactpunt.email"]) if obj.get("Contactpunt.email") is not None else None
        })
        return _obj


