# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.deeltraject_deeltraject_einddatum import DeeltrajectDeeltrajectEinddatum
from openapi_client.models.deeltraject_deeltraject_naam import DeeltrajectDeeltrajectNaam
from openapi_client.models.deeltraject_deeltraject_startdatum import DeeltrajectDeeltrajectStartdatum
from openapi_client.models.deeltraject_deeltraject_status import DeeltrajectDeeltrajectStatus
from openapi_client.models.deeltraject_deeltraject_type import DeeltrajectDeeltrajectType
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_heeft_participatie_inner import PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner
from typing import Optional, Set
from typing_extensions import Self

class Deeltraject(BaseModel):
    """
    Deeltraject
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    deeltraject_naam: Optional[DeeltrajectDeeltrajectNaam] = Field(default=None, alias="Deeltraject.naam")
    deeltraject_startdatum: Optional[DeeltrajectDeeltrajectStartdatum] = Field(default=None, alias="Deeltraject.startdatum")
    deeltraject_einddatum: Optional[DeeltrajectDeeltrajectEinddatum] = Field(default=None, alias="Deeltraject.einddatum")
    deeltraject_type: Optional[DeeltrajectDeeltrajectType] = Field(default=None, alias="Deeltraject.type")
    deeltraject_status: Optional[DeeltrajectDeeltrajectStatus] = Field(default=None, alias="Deeltraject.status")
    deeltraject_heeft_participatie: Optional[Annotated[List[PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner], Field(min_length=0)]] = Field(default=None, alias="Deeltraject.heeftParticipatie")
    __properties: ClassVar[List[str]] = ["@id", "@type", "Deeltraject.naam", "Deeltraject.startdatum", "Deeltraject.einddatum", "Deeltraject.type", "Deeltraject.status", "Deeltraject.heeftParticipatie"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Deeltraject']):
            raise ValueError("must be one of enum values ('Deeltraject')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Deeltraject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deeltraject_naam
        if self.deeltraject_naam:
            _dict['Deeltraject.naam'] = self.deeltraject_naam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deeltraject_startdatum
        if self.deeltraject_startdatum:
            _dict['Deeltraject.startdatum'] = self.deeltraject_startdatum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deeltraject_einddatum
        if self.deeltraject_einddatum:
            _dict['Deeltraject.einddatum'] = self.deeltraject_einddatum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deeltraject_type
        if self.deeltraject_type:
            _dict['Deeltraject.type'] = self.deeltraject_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deeltraject_status
        if self.deeltraject_status:
            _dict['Deeltraject.status'] = self.deeltraject_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in deeltraject_heeft_participatie (list)
        _items = []
        if self.deeltraject_heeft_participatie:
            for _item_deeltraject_heeft_participatie in self.deeltraject_heeft_participatie:
                if _item_deeltraject_heeft_participatie:
                    _items.append(_item_deeltraject_heeft_participatie.to_dict())
            _dict['Deeltraject.heeftParticipatie'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Deeltraject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "Deeltraject.naam": DeeltrajectDeeltrajectNaam.from_dict(obj["Deeltraject.naam"]) if obj.get("Deeltraject.naam") is not None else None,
            "Deeltraject.startdatum": DeeltrajectDeeltrajectStartdatum.from_dict(obj["Deeltraject.startdatum"]) if obj.get("Deeltraject.startdatum") is not None else None,
            "Deeltraject.einddatum": DeeltrajectDeeltrajectEinddatum.from_dict(obj["Deeltraject.einddatum"]) if obj.get("Deeltraject.einddatum") is not None else None,
            "Deeltraject.type": DeeltrajectDeeltrajectType.from_dict(obj["Deeltraject.type"]) if obj.get("Deeltraject.type") is not None else None,
            "Deeltraject.status": DeeltrajectDeeltrajectStatus.from_dict(obj["Deeltraject.status"]) if obj.get("Deeltraject.status") is not None else None,
            "Deeltraject.heeftParticipatie": [PubliekeDienstverleningPubliekeDienstverleningHeeftParticipatieInner.from_dict(_item) for _item in obj["Deeltraject.heeftParticipatie"]] if obj.get("Deeltraject.heeftParticipatie") is not None else None
        })
        return _obj


