# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.deeltraject_concept_skos_definition import DeeltrajectConceptSKOSDefinition
from openapi_client.models.deeltraject_concept_skos_inscheme import DeeltrajectConceptSKOSInscheme
from openapi_client.models.deeltraject_concept_skos_pref_label import DeeltrajectConceptSKOSPrefLabel
from openapi_client.models.deeltraject_concept_skos_top_concept_of import DeeltrajectConceptSKOSTopConceptOf
from typing import Optional, Set
from typing_extensions import Self

class DeeltrajectConcept(BaseModel):
    """
    Deeltraject soort
    """ # noqa: E501
    id: StrictStr = Field(description="URI dat het Concept uniek refereert.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    skos_pref_label: DeeltrajectConceptSKOSPrefLabel = Field(alias="SKOS.prefLabel")
    skos_definition: DeeltrajectConceptSKOSDefinition = Field(alias="SKOS.definition")
    skos_inscheme: Optional[DeeltrajectConceptSKOSInscheme] = Field(default=None, alias="SKOS.inscheme")
    skos_top_concept_of: Optional[DeeltrajectConceptSKOSTopConceptOf] = Field(default=None, alias="SKOS.topConceptOf")
    __properties: ClassVar[List[str]] = ["@id", "@type", "SKOS.prefLabel", "SKOS.definition", "SKOS.inscheme", "SKOS.topConceptOf"]

    @field_validator('id')
    def id_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['https://data.vlaanderen.be/id/conceptscheme/Deeltrajecttype', 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Opleiding', 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Orientering', 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Tender']):
            raise ValueError("must be one of enum values ('https://data.vlaanderen.be/id/conceptscheme/Deeltrajecttype', 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Opleiding', 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Orientering', 'https://data.vlaanderen.be/id/concept/Deeltrajecttype/Tender')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SKOS:Concept', 'SKOS:ConceptScheme']):
            raise ValueError("must be one of enum values ('SKOS:Concept', 'SKOS:ConceptScheme')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeeltrajectConcept from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of skos_pref_label
        if self.skos_pref_label:
            _dict['SKOS.prefLabel'] = self.skos_pref_label.to_dict()
        # override the default output from pydantic by calling `to_dict()` of skos_definition
        if self.skos_definition:
            _dict['SKOS.definition'] = self.skos_definition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of skos_inscheme
        if self.skos_inscheme:
            _dict['SKOS.inscheme'] = self.skos_inscheme.to_dict()
        # override the default output from pydantic by calling `to_dict()` of skos_top_concept_of
        if self.skos_top_concept_of:
            _dict['SKOS.topConceptOf'] = self.skos_top_concept_of.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeeltrajectConcept from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "SKOS.prefLabel": DeeltrajectConceptSKOSPrefLabel.from_dict(obj["SKOS.prefLabel"]) if obj.get("SKOS.prefLabel") is not None else None,
            "SKOS.definition": DeeltrajectConceptSKOSDefinition.from_dict(obj["SKOS.definition"]) if obj.get("SKOS.definition") is not None else None,
            "SKOS.inscheme": DeeltrajectConceptSKOSInscheme.from_dict(obj["SKOS.inscheme"]) if obj.get("SKOS.inscheme") is not None else None,
            "SKOS.topConceptOf": DeeltrajectConceptSKOSTopConceptOf.from_dict(obj["SKOS.topConceptOf"]) if obj.get("SKOS.topConceptOf") is not None else None
        })
        return _obj


