# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.activeringstraject import Activeringstraject
from openapi_client.models.adresvoorstelling import Adresvoorstelling
from openapi_client.models.deeltraject import Deeltraject
from openapi_client.models.domicilie import Domicilie
from openapi_client.models.geregistreerd_persoon import GeregistreerdPersoon
from openapi_client.models.geregistreerde_organisatie import GeregistreerdeOrganisatie
from openapi_client.models.participatie import Participatie
from openapi_client.models.persoon import Persoon
from openapi_client.models.publieke_dienstverlening import PubliekeDienstverlening
from openapi_client.models.publieke_organisatie import PubliekeOrganisatie
from openapi_client.models.verblijfplaats import Verblijfplaats
from openapi_client.models.werkvoorkeuren import Werkvoorkeuren
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

JSONLDROOTGRAPHINNER_ONE_OF_SCHEMAS = ["Activeringstraject", "Adresvoorstelling", "Deeltraject", "Domicilie", "GeregistreerdPersoon", "GeregistreerdeOrganisatie", "Participatie", "Persoon", "PubliekeDienstverlening", "PubliekeOrganisatie", "Verblijfplaats", "Werkvoorkeuren"]

class JsonLdRootGraphInner(BaseModel):
    """
    JsonLdRootGraphInner
    """
    # data type: Werkvoorkeuren
    oneof_schema_1_validator: Optional[Werkvoorkeuren] = None
    # data type: GeregistreerdPersoon
    oneof_schema_2_validator: Optional[GeregistreerdPersoon] = None
    # data type: Persoon
    oneof_schema_3_validator: Optional[Persoon] = None
    # data type: PubliekeOrganisatie
    oneof_schema_4_validator: Optional[PubliekeOrganisatie] = None
    # data type: GeregistreerdeOrganisatie
    oneof_schema_5_validator: Optional[GeregistreerdeOrganisatie] = None
    # data type: Participatie
    oneof_schema_6_validator: Optional[Participatie] = None
    # data type: PubliekeDienstverlening
    oneof_schema_7_validator: Optional[PubliekeDienstverlening] = None
    # data type: Activeringstraject
    oneof_schema_8_validator: Optional[Activeringstraject] = None
    # data type: Deeltraject
    oneof_schema_9_validator: Optional[Deeltraject] = None
    # data type: Verblijfplaats
    oneof_schema_10_validator: Optional[Verblijfplaats] = None
    # data type: Domicilie
    oneof_schema_11_validator: Optional[Domicilie] = None
    # data type: Adresvoorstelling
    oneof_schema_12_validator: Optional[Adresvoorstelling] = None
    actual_instance: Optional[Union[Activeringstraject, Adresvoorstelling, Deeltraject, Domicilie, GeregistreerdPersoon, GeregistreerdeOrganisatie, Participatie, Persoon, PubliekeDienstverlening, PubliekeOrganisatie, Verblijfplaats, Werkvoorkeuren]] = None
    one_of_schemas: Set[str] = { "Activeringstraject", "Adresvoorstelling", "Deeltraject", "Domicilie", "GeregistreerdPersoon", "GeregistreerdeOrganisatie", "Participatie", "Persoon", "PubliekeDienstverlening", "PubliekeOrganisatie", "Verblijfplaats", "Werkvoorkeuren" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = JsonLdRootGraphInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: Werkvoorkeuren
        if not isinstance(v, Werkvoorkeuren):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Werkvoorkeuren`")
        else:
            match += 1
        # validate data type: GeregistreerdPersoon
        if not isinstance(v, GeregistreerdPersoon):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeregistreerdPersoon`")
        else:
            match += 1
        # validate data type: Persoon
        if not isinstance(v, Persoon):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Persoon`")
        else:
            match += 1
        # validate data type: PubliekeOrganisatie
        if not isinstance(v, PubliekeOrganisatie):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PubliekeOrganisatie`")
        else:
            match += 1
        # validate data type: GeregistreerdeOrganisatie
        if not isinstance(v, GeregistreerdeOrganisatie):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeregistreerdeOrganisatie`")
        else:
            match += 1
        # validate data type: Participatie
        if not isinstance(v, Participatie):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Participatie`")
        else:
            match += 1
        # validate data type: PubliekeDienstverlening
        if not isinstance(v, PubliekeDienstverlening):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PubliekeDienstverlening`")
        else:
            match += 1
        # validate data type: Activeringstraject
        if not isinstance(v, Activeringstraject):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Activeringstraject`")
        else:
            match += 1
        # validate data type: Deeltraject
        if not isinstance(v, Deeltraject):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Deeltraject`")
        else:
            match += 1
        # validate data type: Verblijfplaats
        if not isinstance(v, Verblijfplaats):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Verblijfplaats`")
        else:
            match += 1
        # validate data type: Domicilie
        if not isinstance(v, Domicilie):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Domicilie`")
        else:
            match += 1
        # validate data type: Adresvoorstelling
        if not isinstance(v, Adresvoorstelling):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Adresvoorstelling`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in JsonLdRootGraphInner with oneOf schemas: Activeringstraject, Adresvoorstelling, Deeltraject, Domicilie, GeregistreerdPersoon, GeregistreerdeOrganisatie, Participatie, Persoon, PubliekeDienstverlening, PubliekeOrganisatie, Verblijfplaats, Werkvoorkeuren. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in JsonLdRootGraphInner with oneOf schemas: Activeringstraject, Adresvoorstelling, Deeltraject, Domicilie, GeregistreerdPersoon, GeregistreerdeOrganisatie, Participatie, Persoon, PubliekeDienstverlening, PubliekeOrganisatie, Verblijfplaats, Werkvoorkeuren. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Werkvoorkeuren
        try:
            instance.actual_instance = Werkvoorkeuren.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeregistreerdPersoon
        try:
            instance.actual_instance = GeregistreerdPersoon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Persoon
        try:
            instance.actual_instance = Persoon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PubliekeOrganisatie
        try:
            instance.actual_instance = PubliekeOrganisatie.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeregistreerdeOrganisatie
        try:
            instance.actual_instance = GeregistreerdeOrganisatie.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Participatie
        try:
            instance.actual_instance = Participatie.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PubliekeDienstverlening
        try:
            instance.actual_instance = PubliekeDienstverlening.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Activeringstraject
        try:
            instance.actual_instance = Activeringstraject.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Deeltraject
        try:
            instance.actual_instance = Deeltraject.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Verblijfplaats
        try:
            instance.actual_instance = Verblijfplaats.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Domicilie
        try:
            instance.actual_instance = Domicilie.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Adresvoorstelling
        try:
            instance.actual_instance = Adresvoorstelling.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into JsonLdRootGraphInner with oneOf schemas: Activeringstraject, Adresvoorstelling, Deeltraject, Domicilie, GeregistreerdPersoon, GeregistreerdeOrganisatie, Participatie, Persoon, PubliekeDienstverlening, PubliekeOrganisatie, Verblijfplaats, Werkvoorkeuren. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into JsonLdRootGraphInner with oneOf schemas: Activeringstraject, Adresvoorstelling, Deeltraject, Domicilie, GeregistreerdPersoon, GeregistreerdeOrganisatie, Participatie, Persoon, PubliekeDienstverlening, PubliekeOrganisatie, Verblijfplaats, Werkvoorkeuren. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Activeringstraject, Adresvoorstelling, Deeltraject, Domicilie, GeregistreerdPersoon, GeregistreerdeOrganisatie, Participatie, Persoon, PubliekeDienstverlening, PubliekeOrganisatie, Verblijfplaats, Werkvoorkeuren]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


