# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.participatie_participatie_heeft_participant import ParticipatieParticipatieHeeftParticipant
from openapi_client.models.participatie_participatie_rol import ParticipatieParticipatieRol
from typing import Optional, Set
from typing_extensions import Self

class Participatie(BaseModel):
    """
    De rol waarin een Agent deelneemt aan de Publieke Dienstverlening.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    participatie_rol: Optional[ParticipatieParticipatieRol] = Field(default=None, alias="Participatie.rol")
    participatie_heeft_participant: Optional[ParticipatieParticipatieHeeftParticipant] = Field(default=None, alias="Participatie.heeftParticipant")
    __properties: ClassVar[List[str]] = ["@id", "@type", "Participatie.rol", "Participatie.heeftParticipant"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Participatie']):
            raise ValueError("must be one of enum values ('Participatie')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Participatie from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of participatie_rol
        if self.participatie_rol:
            _dict['Participatie.rol'] = self.participatie_rol.to_dict()
        # override the default output from pydantic by calling `to_dict()` of participatie_heeft_participant
        if self.participatie_heeft_participant:
            _dict['Participatie.heeftParticipant'] = self.participatie_heeft_participant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Participatie from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "Participatie.rol": ParticipatieParticipatieRol.from_dict(obj["Participatie.rol"]) if obj.get("Participatie.rol") is not None else None,
            "Participatie.heeftParticipant": ParticipatieParticipatieHeeftParticipant.from_dict(obj["Participatie.heeftParticipant"]) if obj.get("Participatie.heeftParticipant") is not None else None
        })
        return _obj


