# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.contactpunt import Contactpunt
from openapi_client.models.identificator import Identificator
from openapi_client.models.publieke_organisatie_publieke_organisatie_type import PubliekeOrganisatiePubliekeOrganisatieType
from openapi_client.models.publieke_organisatie_publieke_organisatie_voorkeursnaam import PubliekeOrganisatiePubliekeOrganisatieVoorkeursnaam
from typing import Optional, Set
from typing_extensions import Self

class PubliekeOrganisatie(BaseModel):
    """
    Een Organisatie die volgens een wettelijk kader behoort tot de publieke sector, ongeacht het bestuursniveau waarop dat kader van kracht is.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID.", alias="@id")
    type: StrictStr = Field(description="Object type.", alias="@type")
    publieke_organisatie_voorkeursnaam: Optional[PubliekeOrganisatiePubliekeOrganisatieVoorkeursnaam] = Field(default=None, alias="PubliekeOrganisatie.voorkeursnaam")
    publieke_organisatie_contactinfo: Optional[Annotated[List[Contactpunt], Field(min_length=0)]] = Field(default=None, description="Informatie zoals email, telefoon... die toelaat de Organisatie te contacteren.", alias="PubliekeOrganisatie.contactinfo")
    publieke_organisatie_identificator: Optional[Annotated[List[Identificator], Field(min_length=0)]] = Field(default=None, description="Identificator die de organisatie uniek identificeert.", alias="PubliekeOrganisatie.identificator")
    publieke_organisatie_type: Optional[PubliekeOrganisatiePubliekeOrganisatieType] = Field(default=None, alias="PubliekeOrganisatie.type")
    __properties: ClassVar[List[str]] = ["@id", "@type", "PubliekeOrganisatie.voorkeursnaam", "PubliekeOrganisatie.contactinfo", "PubliekeOrganisatie.identificator", "PubliekeOrganisatie.type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PubliekeOrganisatie']):
            raise ValueError("must be one of enum values ('PubliekeOrganisatie')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PubliekeOrganisatie from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of publieke_organisatie_voorkeursnaam
        if self.publieke_organisatie_voorkeursnaam:
            _dict['PubliekeOrganisatie.voorkeursnaam'] = self.publieke_organisatie_voorkeursnaam.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in publieke_organisatie_contactinfo (list)
        _items = []
        if self.publieke_organisatie_contactinfo:
            for _item_publieke_organisatie_contactinfo in self.publieke_organisatie_contactinfo:
                if _item_publieke_organisatie_contactinfo:
                    _items.append(_item_publieke_organisatie_contactinfo.to_dict())
            _dict['PubliekeOrganisatie.contactinfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in publieke_organisatie_identificator (list)
        _items = []
        if self.publieke_organisatie_identificator:
            for _item_publieke_organisatie_identificator in self.publieke_organisatie_identificator:
                if _item_publieke_organisatie_identificator:
                    _items.append(_item_publieke_organisatie_identificator.to_dict())
            _dict['PubliekeOrganisatie.identificator'] = _items
        # override the default output from pydantic by calling `to_dict()` of publieke_organisatie_type
        if self.publieke_organisatie_type:
            _dict['PubliekeOrganisatie.type'] = self.publieke_organisatie_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PubliekeOrganisatie from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "PubliekeOrganisatie.voorkeursnaam": PubliekeOrganisatiePubliekeOrganisatieVoorkeursnaam.from_dict(obj["PubliekeOrganisatie.voorkeursnaam"]) if obj.get("PubliekeOrganisatie.voorkeursnaam") is not None else None,
            "PubliekeOrganisatie.contactinfo": [Contactpunt.from_dict(_item) for _item in obj["PubliekeOrganisatie.contactinfo"]] if obj.get("PubliekeOrganisatie.contactinfo") is not None else None,
            "PubliekeOrganisatie.identificator": [Identificator.from_dict(_item) for _item in obj["PubliekeOrganisatie.identificator"]] if obj.get("PubliekeOrganisatie.identificator") is not None else None,
            "PubliekeOrganisatie.type": PubliekeOrganisatiePubliekeOrganisatieType.from_dict(obj["PubliekeOrganisatie.type"]) if obj.get("PubliekeOrganisatie.type") is not None else None
        })
        return _obj


