# coding: utf-8

"""
    KlantVolgSysteem Release 1

    KlantVolgSysteem 1.0 uitwisseling tussen VDAB en OCMWs via MAGDA. Deze Swagger beschrijft de API voor Release 1. Zonder post.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from openapi_client.models.publieke_dienstverlening_publieke_dienstverlening_finaliteit_skos_pref_label import PubliekeDienstverleningPubliekeDienstverleningFinaliteitSKOSPrefLabel
from typing import Optional, Set
from typing_extensions import Self

class PubliekeDienstverleningPubliekeDienstverleningFinaliteit(BaseModel):
    """
    Wettelijk kader waarvoor de informatie wordt bevraagd.
    """ # noqa: E501
    id: StrictStr = Field(description="Object ID. Can be an URI or internal reference such as _:MyID. Must point to a FinaliteitType enum value URI.", alias="@id")
    skos_pref_label: PubliekeDienstverleningPubliekeDienstverleningFinaliteitSKOSPrefLabel = Field(alias="SKOS.prefLabel")
    __properties: ClassVar[List[str]] = ["@id", "SKOS.prefLabel"]

    @field_validator('id')
    def id_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['https://data.vlaanderen.be/id/concept/FinaliteitType/SociaalOnderzoek', 'https://data.vlaanderen.be/id/concept/FinaliteitType/GPMI']):
            raise ValueError("must be one of enum values ('https://data.vlaanderen.be/id/concept/FinaliteitType/SociaalOnderzoek', 'https://data.vlaanderen.be/id/concept/FinaliteitType/GPMI')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PubliekeDienstverleningPubliekeDienstverleningFinaliteit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of skos_pref_label
        if self.skos_pref_label:
            _dict['SKOS.prefLabel'] = self.skos_pref_label.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PubliekeDienstverleningPubliekeDienstverleningFinaliteit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "@id": obj.get("@id"),
            "SKOS.prefLabel": PubliekeDienstverleningPubliekeDienstverleningFinaliteitSKOSPrefLabel.from_dict(obj["SKOS.prefLabel"]) if obj.get("SKOS.prefLabel") is not None else None
        })
        return _obj


