from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ErrorMessage")


@_attrs_define
class ErrorMessage:
    """A representation of a generic error message.

    Attributes:
        title (str): A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to
            occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation.
        detail (str): A human-readable explanation specific to this occurrence of the problem.
        type_ (str | Unset): A URI reference that identifies the problem type. This specification encourages that, when
            de-referenced, it provide human-readable documentation for the problem type. When this member is not present,
            its value is assumed to be about:blank.
        status (str | Unset): The HTTP status code generated by the origin server for this occurrence of the problem.
        instance (str | Unset): A URI reference that identifies the specific occurrence of the problem. It may or may
            not yield further information if de-referenced.
    """

    title: str
    detail: str
    type_: str | Unset = UNSET
    status: str | Unset = UNSET
    instance: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        title = self.title

        detail = self.detail

        type_ = self.type_

        status = self.status

        instance = self.instance

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "title": title,
                "detail": detail,
            }
        )
        if type_ is not UNSET:
            field_dict["type"] = type_
        if status is not UNSET:
            field_dict["status"] = status
        if instance is not UNSET:
            field_dict["instance"] = instance

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        title = d.pop("title")

        detail = d.pop("detail")

        type_ = d.pop("type", UNSET)

        status = d.pop("status", UNSET)

        instance = d.pop("instance", UNSET)

        error_message = cls(
            title=title,
            detail=detail,
            type_=type_,
            status=status,
            instance=instance,
        )

        error_message.additional_properties = d
        return error_message

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
